export interface CloseTransaction {
    clt_closed_ID:string;
    clt_100_bills:number;
    clt_50_bills:number;
    clt_20_bills:number;
    clt_10_bills:number;
    clt_5_bills:number;
    clt_1_bills:number;
    clt_checks_amount:number;
    clt_credits_amount:number;
    clt_total_charged:number;
    clt_total_cash:number;
    clt_total_check:number;
    clt_total_credit:number;
    clt_initial_cash:number;
    clt_balance:number;
    clt_transaction_count:number;
    clt_reg_RegisterID:string;
    clt_Username:string;
    clt_Datetime:string;
}
